### ISSUE TITLE
Icon "enhanced_browsing" doesn't suit start menu

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#12]
Commit [308e753df952751d65ddcfad94e20a0b9546157b](https://github.com/jaerrib/waterleaf-icon-theme/commit/308e753df952751d65ddcfad94e20a0b9546157b) has added "enhanced_browsing" icon. The icon is also used in the Q4OS start menu - web search option, so users see it very frequently. The previous icon wasn't perfect, but still looked a bit better in the start menu. Please see the pictures attached.

Before commit:
![snp1](https://user-images.githubusercontent.com/16801039/68472408-bf4e2500-0220-11ea-8abe-1eebac4f5578.png)
After commit:
![snp2](https://user-images.githubusercontent.com/16801039/68472409-c1b07f00-0220-11ea-82ff-67508adde50a.png)

We would need a less bold icon here, so we suggest to modify "enhanced_browsing" icon to be less distinctive, more symbolic black/white, alternatively grey. If the change would break an original intended purpose, let the "enhanced_browsing" icon as is. It that case, we need to design a new icon dedicated for the start menu exclusively and make a subsequent modifications of the tde-base source code.

Style reference:
![snp3](https://user-images.githubusercontent.com/16801039/68472570-0f2cec00-0221-11ea-9502-4d90c8e0e89b.png)
Example:
![snp6](https://user-images.githubusercontent.com/16801039/68472632-2d92e780-0221-11ea-8bd1-ab0f0b01b03f.png)

**Comment by jaerrib** [comment]
The commit was made so that the icon for Web Shortcuts in Konqueror's settings menu wouldn't fall back to hicolor. I'm not opposed to using the magnifying glass icon or designing something that would look nice in either location though. Do you have a preference? Also, do you know offhand if the icon that shows up in the menu uses or just points to the enhanced_browsing icon?

**Comment by q4osteam** [comment]
Commit https://github.com/jaerrib/waterleaf-icon-theme/commit/b36f8bf23756212ff5aa302c72105e07b4db33e5 resolves the issue, you we can close it now, thanks.

For an info, the icon name "enhanced_browsing" is hardcoded in the Kickoff as well as Bourbon menu source code.
