### ISSUE TITLE
Waterleaf on top of Papirus

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#18]
We have made some testing about Papirus icon theme and Q4OS. Since Papirus project enables folder icons coloring, we are considering a possibility to start a new experimental branch within the Waterleaf project based on Papirus icon theme with some small overlay of the original Waterleaf icons. All folder icons would be recolored into the nice Waterleaf style.

The first phase should be comprised from a Papirus folder icons coloring conversion script and establishing a list of complementary Waterleaf icons. As a result, we could get rather small project sitting on top of the great Papirus icons theme. As a huge bonus, all this Waterleaf branch would contain all icons in .svg format.

@Jaerib
We have a first experimental script and a few related files prepared, so if you would agree a new branch could be started. What do you think about that idea ?

**Comment by q4osteam** [comment]
As you can see, Plasma desktop with Papirus icons recolored looks fine already, unlike TDE desktop, that will need some tuning.

Q4OS Plasma desktop with Papirus icons, recolored folders.
![q4os_papirus_plasma](https://user-images.githubusercontent.com/16801039/87918399-aa47b800-ca76-11ea-8bff-3439c43b668c.png)

Q4OS Trinity desktop with Papirus icons, recolored folders.
![q4os_papirus_tde](https://user-images.githubusercontent.com/16801039/87918410-acaa1200-ca76-11ea-95ab-efca89f633c6.png)

**Comment by jaerrib** [comment]
That's a great idea. Is the proposal to be able to use the script and incorporate any missing TDE icons on the Papirus repo? Or is it forking Papius at a certain point in time and building on it?

I like the idea of the script working on their repo because we can enjoy that team's improvements and missing TDE icons could be contributed upstream. Maintaining a fork, as we've done with Paper, has evolved into a bit of a Frankenstein theme over time. Don't get me wrong, it works, but it's a varied assortment of styles.

**Comment by q4osteam** [comment]
The objective is not to maintain a complete theme fork. The new branch would include only:
1. A small set of original Waterleaf icons, that are missing in Papirus theme, or they don't match Waterleaf style. We may make a pull request for Papirus development team to include such icons into the Papirus directly, before we add them to the Waterleaf.
2. A script to generate Waterlaef icon theme. The input of the script would be the Papirus icon theme package and set of original Waterleaf icons. Script would generate completed Waterleaf icon set, with folders recolored to the Waterleaf style.

Of course, it would be great and preferred way to synchronize both projects and ask Papirus team to include existing Waterleaf icons into Papirus. In cases they refuse for some reason, we will include such icons into the Waterleaf project directly.

**Comment by jaerrib** [comment]
I definitely like the idea of maintaining a more minimal icon theme rather than forking such a large project. Since the original Waterleaf icons have all been created as SVG files, it should make modernizing the theme much less daunting that converting all of the old Paper-based icons since Papirus is a much bigger project and have already done all of that heavy lifting. I know there's also been some effort from that team to add some TDE specific icons already, but there are some nuances that we've done on our end for Waterleaf which will need to be addressed, as you've illustrated already. I'll go ahead and create the branch so that we can get started. Thanks for taking the initiative on this; I'm looking forward to seeing where it goes!

On a related note, does the script look for local input, or does it look somewhere online? It might be interesting if it could grab the Debian package and build on that to keep things on the stable side.

**Comment by q4osteam** [comment]
Well, that sounds great. We will post an initial version of the script and a list of overlay Waterleaf icons, hopefully tomorrow. The script could feature a parameter, where to get the Papirus package. It's possible to clone Papirus online from their Github repository, download from Debian repositories, or grab the package locally as well.

**Comment by jaerrib** [comment]
Just a thought, but considering the experimental branch is pre-populated with everything from the development branch, would it be better to create a new repo for this project to keep the code base cleaner? (Maybe not though...if this method works out better, all of the old code can be streamlined or removed. Thoughts?)

**Comment by q4osteam** [comment]
A branch might be better for now. Is it possible to remove everything from the branch, that doesn't fall into it ?

**Comment by jaerrib** [comment]
There should be a way to create an empty branch (although at least one commit is required for it to show up) or remove the unneeded files. The problem for me is that I'm not familiar with using git from the cli. I use Github's web interface or GitKraken. That said, I can learn, and I will look into how to do it.

**Comment by q4osteam** [comment]
Yes, creating an empty branch is what we need.

**Comment by jaerrib** [comment]
From what I'm reading, it would seem that merging orphan branches into the master is awkward at best and may complicate things a bit. I'm no git wizard so, while I could stumble around and set up a blank branch, it would be troublesome for me to ever merge it. I suggest a new repo unless there's no plan to ever merge and replace the theme as it sits right now. Is anyone on the Q4OS team more comfortable with git?

**Comment by q4osteam** [comment]
Please do what you mean is the most convenient. Anyway, merging to master doesn't seem to be so complicated, just remove all files from master, commit, and place new files to the emptied master. But we have no experience here, so cannot say for sure.

**Comment by jaerrib** [comment]
My understanding is that the level of complication is based on how much code you want to bring in from the orphan branch. You're looking to _replace_ rather than _merge_ which is likely much easier. To be safe, I may push the experimental branch to development before master. Either way, the empty orphan branch (minus README.md) has been created here: [https://github.com/jaerrib/waterleaf-icon-theme/tree/experimental](https://github.com/jaerrib/waterleaf-icon-theme/tree/experimental)

**Comment by q4osteam** [comment]
Great, we will load the new branch with initial set of files, however it could take a while, as we are busy with another more important tasks now. Anyway it should not last long.

**Comment by q4osteam** [comment]
We have populated the experimental branch with a few files. Please copy all files into a folder and run the script "sh 99_generate_waterleaf.sh". It will clone all needed for the first time, and generate Waterleaf icon theme into output directory.

The script doesn't copy anything from original Waterleaf icons so far, just recolors folders and does some editing in Papirus index.theme file.

Now we would need to continue with the following:
1. Look over Plasma and Trinity Debonaire themes and polish them as much as possible to follow the nice Debonaire style, see the following point 2.
2. Establish a list of original Waterleaf icons to override the Papirus counterparts, or complete the missing ones. First it could be requested to pull them into Papirus directly.

Please look at the script source code, it's commented and rather transparent. Any changes, improvements, suggestions are welcome.

**Comment by jaerrib** [comment]
Thanks for uploading what you have so far. I'll look over the script and determine which icons we need to override or import then post any input I might have. Is the script targeted at a specific version of Q4OS?

**Comment by q4osteam** [comment]
The script is intended to be usable on any generic Linux distribution, however tested on Q4OS 3 Centaurus only at the moment.

We assume Waterleaf, as well as Papirus icon set, should be designed as a generic set applicable on any Plasma/Trinity desktop Linux distribution. However, we are able to perform a testing to achieve the best visual results with Debonaire theme on the current stable Q4OS 3 Centaurus systems with Plasma and Trinity desktops.

**Comment by jaerrib** [comment]
A fresh install of Centaurus with the Basic desktop profile does not include git so the script failed initially. Installing git, then running the script was successful. Everything appears to build correctly. However, with Lookswitcher installed, Waterleaf obviously gets installed as well. Is there a preferred way of visually testing the icon theme that gets build by the script?

**Comment by q4osteam** [comment]
Just replace the "/usr/share/icons/Waterleaf" directory with the generated one, perform a system reboot and check the theme.

**Comment by q4osteam** [comment]
You also need to install "lookswitcher-plasma" package for Plasma and "lookswitcher" for Trinity desktop. Switch the desktop to Debonaire theme using lookswitcher tool and then replace the "/usr/share/icons/Waterleaf" directory as described in the previous post.

**Comment by q4osteam** [comment]
You may also need to reuse Waterkeaf icon theme and reboot for sure, after replacing the "/usr/share/icons/Waterleaf" directory.

**Comment by q4osteam** [comment]
For an illustration, images of Debonaire theme before and after using the experimental Waterleaf icon set.

Before:
![s1](https://user-images.githubusercontent.com/16801039/88487618-28302580-cf87-11ea-9c40-367c08d4c34b.png)

After:
![s2](https://user-images.githubusercontent.com/16801039/88487626-2f573380-cf87-11ea-954b-c6c734217b29.png)

**Comment by q4osteam** [comment]
Screenshots before and after applying the experimental Waterleaf icon set, just for an illustration.

Before:
![s1](https://user-images.githubusercontent.com/16801039/88489827-279f8b00-cf97-11ea-9927-ba69d5c98b52.png)

After:
![s2](https://user-images.githubusercontent.com/16801039/88489829-2cfcd580-cf97-11ea-8689-d5c80280c676.png)

**Comment by q4osteam** [comment]
We have updated the main script to replace selected Papirus icons with their counterparts from Waterleaf theme, so we need to complete the list in "70_waterleaf_icons.lst" file by icons to be overridden.

**Comment by jaerrib** [comment]
All of your suggestions have been helpful. I'm currently looking through the differences between the script-created version of Waterleaf and the version on the development branch. Of course, the development version still has a number of png files, which Papirus replaced. No problems dropping those, of course. It also appears that Papirus has already incorporated a number of TDE-specific icons. I like what they've done so it'll just be a matter of choice with regard to style. (We can lean towards existing Waterleaf icons if you prefer.) Some notable icons that are missing, such as the My Documents icon, are technically present in the script-created version but don't display in Trinity. I'll have to go through and find where some of those DE-specific icons/symlinks are.

For situations where an svg icon is present in Waterleaf but not Papirus, can the script be made to copy those into the generated theme? (For example, the UI icons that had been created for amarok-trinity.)

In the meantime, I'll work on the override list and make note of any other issues I come across.

**Comment by q4osteam** [comment]
Yes, we need to look the incorrect Trinity icons up and replace them in the experimental Waterleaf theme. The script should be able to copy missing icons as well, so we only need to add them to the "70_waterleaf_icons.lst" file. For example, the UI icons that had been created for amarok-trinity. The other way would be to ask Papirus development team to include such icons into the Papirus theme.

**Comment by jaerrib** [comment]
I added a number of icons to the override list (70_waterleaf_icons.lst). There are a couple other issues which I'm not sure how to address.
- There needs to be a symlink from places/folder_wordprocessing pointing to folder-waterleaf-documents. This should fix the broken MyDocuments folder under TDE
- There needs to be a symlink from places/folder_man pointing to folder-waterleaf-documents. This will fix the issue with a blue Documents Folder icon showing up in Konqueror when clicking on My Computer.
- There needs to be a symlink from places/folder_man2 pointing to folder-waterleaf-image-people. This will fix the issue with a blue Users Folder icon showing up in Konqueror when clicking on My Computer.

Are these symlinks that can be applied in the Waterleaf base? Should it be an upstream fix? (minus the specific Waterleaf part, of course) Is it something that can be added with the script?

As far as style goes, do you prefer the current Waterleaf design for updatemgr, login manager, user and groups, and service manager or would like to stick with the Papirus defaults?

**Comment by q4osteam** [comment]
We will take a look on the issues mentioned and post back in a few days.

**Comment by jaerrib** [comment]
I did some experimenting with the symlink suggestions I had made. As you can see from the attached image, the various documents folders are indeed fixed with those changes. There's still the question of how it gets implemented, whether it's via the script, upstream in Papirus, etc., but I like the new look overall.

![fixed folders](https://user-images.githubusercontent.com/24616239/90699281-dcecf800-e250-11ea-99b9-9e46c5ce8720.png)

**Comment by jaerrib** [comment]
One additional symlink pointing from folder_locked to folder-waterleaf-locked fixes the lost&found folder from falling back to crystalsvg as well.

![fixed folders2](https://user-images.githubusercontent.com/24616239/90699714-fcd0eb80-e251-11ea-9c44-b750d43b6e25.png)

**Comment by q4osteam** [comment]
That looks good. The most preferred method would be to implement as many as possible modifications via Papirus upstream. In any case, we are considering some script updates so that the necessary symlinks can be placed. Hopefully it will be ready in a few days.

**Comment by q4osteam** [comment]
We have pushed a new commit a6b3606fdb533407e1717a1b3490194663a11f8a . The script can now place symbolic links as well as regular icons into the target theme. So it's possible to place symlinks you mentioned in the earlier posts to the "70_waterleaf_icons.lst" file, they will override Papirus counterparts.

The source icon theme has been switched to the Waterleaf "development" branch. At the same time we would suggest to populate experimental branch with all the icons needed, and then change the script to get icons from the experimental instead of development branch.

To answer the previous question, we would prefer to stick with the default Papirus icons as much as possible, however we could override more of them over time.

**Comment by jaerrib** [comment]
> That looks good. The most preferred method would be to implement as many as possible modifications via Papirus upstream. In any case, we are considering some script updates so that the necessary symlinks can be placed. Hopefully it will be ready in a few days.

I'll take a look at upstream to see which symlinks they require. At least one of their contributors has a goal of better supporting TDE so I would expect the project to be open to filling out anything that might be missing.

**Comment by jaerrib** [comment]
> We have pushed a new commit [a6b3606](https://github.com/jaerrib/waterleaf-icon-theme/commit/a6b3606fdb533407e1717a1b3490194663a11f8a) . The script can now place symbolic links as well as regular icons into the target theme. So it's possible to place symlinks you mentioned in the earlier posts to the "70_waterleaf_icons.lst" file, they will override Papirus counterparts.
>
Thanks for updating the script!
> The source icon theme has been switched to the Waterleaf "development" branch. At the same time we would suggest to populate experimental branch with all the icons needed, and then change the script to get icons from the experimental instead of development branch.
>
While I haven't uploaded anything yet, I am working on an 'override_icons' folder which will have the very function.
> To answer the previous question, we would prefer to stick with the default Papirus icons as much as possible, however we could override more of them over time.
>
For the sake of completion, I'll work on getting all of the created icons and relevant symlinks into the override folder and listed in the "70_waterleaf_icons.lst" file. If there's anything out of sorts, we can comment out where the default Papirus icon is preferred and then modify the override folder as necessary,

**Comment by q4osteam** [comment]
We would suggest to shift the experimental branch to the development now, as the new Waterleaf icons are used, and so tested as well, within the upcoming stable Q4OS Gemini edition.

**Comment by jaerrib** [comment]
@q4osteam My apologies for leaving this project abandoned for so long. The experimental and development/master branches have different commit histories so a traditional pull request can't be done. If I were to simply copy the experimental files to the development branch, what deletions would be necessary to make the patch compatible? Does it just reference the files in the Waterleaf folder?

**Comment by q4osteam** [comment]
Hello, nice to see the projects shifts further :) First you need to switch to the development branch. Remove all files in the development branch and replace them with the new files locally. Subsequently make a new commit and push to the remote repository.
