### ISSUE TITLE
Network manager icons misshapen in TDE

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#5]
Network manager icons misshapen in TDE, at least for 32 size, see the picture:
![issue1](https://user-images.githubusercontent.com/16801039/66819297-0bb68580-ef3f-11e9-865f-963d85a19449.png)

**Comment by jaerrib** [comment]
I can confirm the bug. What's odd is that I don't see it in Inkscape or when viewing the preview in Dolphin. Either way, I'll take a look. I'm thinking it may be something to do with fractional pixel positioning. I may end up tweaking the design somewhat to be more in line with Advanced Network Configuration icon, which has the "globe" positioned vertically instead of on a slant and doesn't seem to exhibit the same issue,

**Comment by jaerrib** [comment]
After reworking the icon to use the spacing as described in the developer's guide (and slightly tweaking the middle portion of the icon), I was able to correct the issue.

**Before:**
![network_before](https://user-images.githubusercontent.com/24616239/67058708-01a1ac00-f124-11e9-9d9a-7e8c98ce27af.png)

**After:**
![network_after](https://user-images.githubusercontent.com/24616239/67058718-0b2b1400-f124-11e9-929a-b4f4f6340cd1.png)

I'll work on both the normal and disabled variations of the icon in all the sizes and upload those in te next day or so.

**Comment by q4osteam** [comment]
Yes, that looks perfect.

**Comment by jaerrib** [comment]
I pushed the changes for all sizes on both icons to the development branch ([2920e98](https://github.com/jaerrib/waterleaf-icon-theme/commit/2920e98aed44968e97b7c6b3f658be5388c394e8)). They are also revised to use the new standards listed in the developer's guide. If everything is good, I'll mark the issue as closed.

**Comment by q4osteam** [comment]
Looks fine now for sizes >= 32, however another distortion arose in 16 and 24, see screenshots before and after the (2920e98) update.

Before:
![issue6a](https://user-images.githubusercontent.com/16801039/67186563-9dfbd500-f3e8-11e9-9dca-bf4bacc1997b.png)
After:
![issue6b](https://user-images.githubusercontent.com/16801039/67186581-a3f1b600-f3e8-11e9-83ea-9c3437d7f360.png)

**Comment by q4osteam** [comment]
We have tested the latest development snapshot post (b8d6808) and the issue looks to be fixed. Great job, thanks.
