### ISSUE TITLE
Colors merge in the white background for Konqeror and some other icons

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#6]
This is a regression. It relates to:
konqeror
tdevelop
kdevdesigner

In the previous stable waterleaf-icon-theme_20190804 https://github.com/jaerrib/waterleaf-icon-theme/releases/tag/20190804 release the Konqueror cogwheel had a shade of gray, while in the latest release it is colorized somewhat. The new colorization merges in a lighter backgroud, see the pictures:

![issue2b](https://user-images.githubusercontent.com/16801039/66825406-7d480100-ef4a-11e9-8f70-0bce7778b4b3.png)
![issue2a](https://user-images.githubusercontent.com/16801039/66825509-aec0cc80-ef4a-11e9-9bbd-4427dc2e2a92.png)

We would suggest to use a bit darker shade of gray for the cogwheel, as it should give much better experience.

**Comment by jaerrib** [comment]
The color change came about when I updated the color palette from Elementary to Paper. I can use the same palette but try using a darker variation of the cog wheel color to differentiate it from the background

**Comment by q4osteam** [comment]
We would prefer a less intensive color for the cogwheel, anyway it needs to be a bit darker to differentiate it from the white background.

**Comment by jaerrib** [comment]
Two possible alternate colors for the cog wheel. The color of the first is probably closer to the original you preferred but now uses the Paper/Waterleaf palette. However, the the shadow tends to blend in with this particular shade. The second one has more differentiation between those elements and may also stand out better against a lighter background.
![konqueror_recolor](https://user-images.githubusercontent.com/24616239/67057949-aa4e0c80-f120-11e9-8405-58860e17b983.png)
![konqueror_recolor2](https://user-images.githubusercontent.com/24616239/67057956-af12c080-f120-11e9-89a1-4d47bbc6704a.png)

**Comment by q4osteam** [comment]
We will test them and post a results, thanks for the samples.

**Comment by q4osteam** [comment]
Both look fine throughout the testing, maybe the second one makes a slightly better experience. Nonetheless, you are welcome to choose any by your preferences.

**Comment by jaerrib** [comment]
Color change made for all three icons. If they test okay, I will close the bug as being fixed.

**Comment by q4osteam** [comment]
Konqueror and Tdevelop icons look perfect now, however we have noticed most likely incorrect, black, shadow at the bottom of kdevdesigner icon, see the picture. It's related only to the "kdevdesigner" for sizes > 32

Black shadowing:
![issue7a](https://user-images.githubusercontent.com/16801039/67187189-faabbf80-f3e9-11e9-8c76-8272ecdba30c.png)

**Comment by q4osteam** [comment]
Looks to be fixed now, thanks for the great work.
