### ISSUE TITLE
Consider to revert colors of a few icons

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#7]
This is not an issue, more likely a proposal for consideration.

After testing the new stable release https://github.com/jaerrib/waterleaf-icon-theme/releases/tag/20190914 for a while, we would suggest to revert back to original coloring of the following icons:
- blockdevice
- synaptic
- q4os-swcentre

It seems the original colorization gave a better impression. Anyway, we are aware it's a subjective point of view. Shapes and other icons properties are fine, it's about colors only.

1. See the new icons in action:
![n2](https://user-images.githubusercontent.com/16801039/66826614-22fc6f80-ef4d-11e9-84e7-86ace5cf5536.png)
2. In comparison to the old ones:
![o2](https://user-images.githubusercontent.com/16801039/66826621-27c12380-ef4d-11e9-9446-75625391db3c.png)

**Comment by jaerrib** [comment]
I'm not opposed to reverting the colors to the previous versions. The changes were my attempt at bringing the color scheme more in line with the original Paper palette whereas I had been using the one from Elementary before. The latest versions were, perhaps, a bit too bold and a softer look may be better.

Specifically regarding the blockdevice, what would you think of the same color grouping (blue, yellow, green) if they were less intense? Or, do you prefer the purple, orange, and green grouping?

**Comment by q4osteam** [comment]
From our subjective point of view, the three icons in question fitted better in the overall theme look with the original coloring. For a wonder using the Elementary palette :)

Making the new colors less intense could be a proper way too, however we are not able to assess that without a working sample. In general, we consider a less intensive coloring for the Waterleaf icons more appealing.

**Comment by jaerrib** [comment]
Here are two possibilities for recolored versions alongside the original (which actually has an error on the green block...) and the reworked variation. They're both using the Elementary palette again though.
![blockdevice](https://user-images.githubusercontent.com/24616239/67057436-783bab00-f11e-11e9-8130-5e23af3e06f3.png)
Here's a third choice that actually uses the Paper/Waterleaf color palette. It's probably the "softest" looking of all of them, but the yellow might be too light.
![blockdevice-recolor3](https://user-images.githubusercontent.com/24616239/67057458-92758900-f11e-11e9-8fc7-48d9f78ae514.png)

**Comment by q4osteam** [comment]
The new looks fine, we will make a brief testing and put findings and an opinion here in a few days.

**Comment by jaerrib** [comment]
I've made changes to all three of the icons you mentioned ([be8eod4](https://github.com/jaerrib/waterleaf-icon-theme/commit/b8e0d4019323a70a4d939f7a7ae37b01fe5427d0), [568128f](https://github.com/jaerrib/waterleaf-icon-theme/commit/568128f16213f81ee8bc391421ec86a6ffa75b00), [1eddfd6](https://github.com/jaerrib/waterleaf-icon-theme/commit/1eddfd69a79b6f36c161503f778aac3ef6e9950b)).

I went with recolor version 3 for blockdevice. The brown for the software store isnt quite the same as the original (which was from the Elementary palette) but it's much closer than the current version. I tried to balance the colors for Synaptic to maintain consistency with the Paper/Waterleaf palette while still trying to have something similar to the original icon. If you're okay with the changes, I'll mark this as closed.

**Comment by q4osteam** [comment]
1. We have noticed incorrect, black, shadow at the bottom of all three icons, see the picture:
![issue8a](https://user-images.githubusercontent.com/16801039/67187557-bff65700-f3ea-11e9-8f08-f20a65a9747e.png)

Apart from the black shadowing, icons fit nice in the TDE Debonaire theme.

**Comment by jaerrib** [comment]
All sizes or just a specific one?

**Comment by q4osteam** [comment]
Apparently for all the shadowed sizes, so higher then 32

**Comment by jaerrib** [comment]
Can you check the icon in this [zip file](https://github.com/jaerrib/waterleaf-icon-theme/files/3759120/blockdevice.zip)? (Github doesn't allow attaching svg files directly.) I changed the color of the shadow to "inherit" instead of being black. If that doesn't fix the issue, it's likely a positioning problem with the shadow, and I'll have to try another approach.

**Comment by q4osteam** [comment]
Yes, that looks right

48 size
![issue9a](https://user-images.githubusercontent.com/16801039/67382521-e7395980-f58d-11e9-94a8-283bb63fbfde.png)

128 size
![issue9b](https://user-images.githubusercontent.com/16801039/67382529-e99bb380-f58d-11e9-85c6-171a77f512cc.png)

**Comment by q4osteam** [comment]
Shadowing is now correct. The softer look of the new icons versions fit much better in the Debonaire theme and they look neat. Great job, thanks.
