### ISSUE TITLE
Waterleaf icons composition guidelines

### ISSUE THREAD

**Issue by q4osteam** [jaerrib/waterleaf-icon-theme#8]
This is not an issue, more likely a space for discussion on the developer guidelines http://htmlpreview.github.com/?https://github.com/jaerrib/waterleaf-icon-theme/blob/development/dev_guide/waterleaf_guide.html

**Comment by q4osteam** [comment]
In the latest update, you have set the baseline value as "2" for canvas "24".
![issue4a](https://user-images.githubusercontent.com/16801039/66827965-30672900-ef50-11e9-839b-b38bb4e1b4c9.png)
Shouldn't it to be "1" ?

**Comment by jaerrib** [comment]
I had based those numbers on the Elementary Human Interface Guidelines as a starting point. Since the x-height for Waterleaf is slightly larger, it's probably safe to change it to "1" for canvas "24". I went ahead and updated the developer's guide with the change.
